import { StyleSheet, Dimensions } from "react-native";
import { colors } from "../../../constants/color";

const width = Dimensions.get("window").width;
const height = Dimensions.get("window").height;

export const sliderStyles = StyleSheet.create({
    labelWrapper: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
    },
    labelText: {
        fontSize: 20,
        fontWeight: "bold",
    },
    labelTxt: {
        fontSize: 16,
        fontWeight: "bold",
        padding: 16,
        paddingBottom: 5,
    },
});

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        height: "100%",
    },
    contentStyle: {
        paddingVertical: 16,
        paddingBottom: 100
    },
    searchBoxWrapper: {
        height: height / 22.55,
        margin: 16,
        marginBottom: 0,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#E5E5E7",
        borderRadius: 10,
        paddingHorizontal: 16,
    },
    searchBox: {
        height: "100%",
        flexDirection: "row",
        alignItems: "center",
    },
    searchBtn: {
        paddingRight: 5,
        height: "80%",
        justifyContent: "center",
        alignItems: "center",
    },
    filterBox: {
        height: height / 20,
        paddingHorizontal: 16,
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    headerText: {
        textAlign: "center",
        fontSize: 16,
        fontWeight: "500",
    },
    hiddenContent: {
        height: height / 3.2,
        backgroundColor: "#F5F5F5",
    },
    picker: {
        flex: 1,
        height: "100%",
        backgroundColor: "#eee",
        color: "#B8B8BB",
    },
    inputContainer: {
        width: "100%",
        height: height / 15,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#fff",
        paddingHorizontal: 16,
    },
    preTextWrapperStyle: {
        flex: 1,
        height: "100%",
        justifyContent: "center",
        width: width * 0.3,
    },
    preText: {
        fontSize: 16,
    },
    phoneTxtWrapper: {
        height: height / 15,
        paddingHorizontal: 16,
        justifyContent: "center",
    },
    phoneTxt: {
        color: colors.gray,
        fontSize: 16,
    },
    addressTxt: {
        color: "black",
        fontSize: 16,
        fontWeight: "bold",
    },
    input: {
        width: "100%",
        height: "100%",
        flex: 1,
        fontSize: 16,
        color: "#666",
    },
    pickerWrapper: {
        height: height / 15,
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: "#fff",
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    resetWrapper: {
        height: height / 15,
        width: "100%",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
        paddingHorizontal: 16,
    },
    resetText: {
        fontSize: 16,
        color: "#E50000",
    },
    hideButtonWrapper: {
        height: height / 15,
        width: "100%",
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        paddingHorizontal: 16,
    },
    hideButtonText: {
        fontSize: 16,
        color: "#E50000",
    },
    divider: {
        borderBottomColor: "black",
        borderBottomWidth: 0.9,
        marginHorizontal: 16,
        marginVertical: 24,
    },
    resultBox: {
        height: height / 3.98,
        backgroundColor: "gray",
        borderRadius: 15,
        marginHorizontal: 16,
        marginBottom: 16,
        borderColor: "#EDEDED",
        borderWidth: 1,
        overflow: "hidden",
    },
    resultLineBox: {
        width: "100%",
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        backgroundColor: "white",
        borderBottomWidth: 1,
        borderBottomColor: "#EDEDED",
    },
    resultId: {
        flexDirection: "row",
        width: "30%",
        justifyContent: "space-between",
    },
    resultIdText: {
        fontSize: 16,
        fontWeight: "bold",
    },
    locationStyle: {
        padding: 2,
        borderWidth: 1,
        borderColor: colors.lightGray,
        borderRadius: 10,
    },
    resultFullName: {
        fontSize: 16,
        fontWeight: "bold",
        textAlign: "center",
    },
    resultPhoneNumbers: {
        flex: 1,
        fontSize: 16,
    },
    fab: {
        width: 64,
        height: 64,
        borderRadius: 32,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        bottom: 28,
        left: 24,
        backgroundColor: "#2196F3",
    },
    fab2: {
        width: 64,
        height: 64,
        borderRadius: 32,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        bottom: 28,
        right: 24,
        backgroundColor: "#2196F3",
    },
    fab3: {
        width: 64,
        height: 64,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: colors.lightGray,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        bottom: 100,
        right: 24,
        backgroundColor: "white",
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
    },
    fab4: {
        width: 64,
        height: 64,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: colors.lightGray,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        bottom: 28,
        right: 24,
        backgroundColor: "white",
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
    },
    onSelectDel: {
        fontSize: 12,
        color: colors.red
    },
    onSelectNot: {
        fontSize: 12,
        color: colors.blue
    },
    centeredView: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: 'rgba(0,0,0,0.5)'
    },
    modalWrapper: {
        width: "70%",
        height: "30%",
        shadowColor: "#000",
        borderRadius: 20,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        backgroundColor: "white",
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        overflow: "hidden",
        marginBottom: 10,
    },
    deleteModalWrapper: {
        width: "80%",
        height: "20%",
        shadowColor: "#000",
        borderRadius: 20,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        backgroundColor: "white",
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        overflow: "hidden",
        marginBottom: 10,
    },
    clientAddress: {
        width: "100%",
        height: "66%",       
        backgroundColor: "white",
        overflow: "hidden",
        justifyContent: "center",
        alignItems: "flex-start",
        paddingHorizontal: 15,
        borderBottomColor: colors.lightGray,
        borderBottomWidth: 1
    },
    genderModalWrapper: {
        height: "15%",
    },
    contenModalView: {
        flex: 1,
        height: "100%",
    },
    deleteModalContent: {
        flex: 1,
    },
    deleteModalText: {
        height: "66%",
        width: "100%",
        textAlign: "center",
        textAlignVertical: "center",
        borderBottomColor: colors.gray,
        borderBottomWidth: 1,
        fontSize: 16,
        fontWeight: "bold",
    },
    deleteModalBtns: {
        flexDirection: "row",
        height: "33%",
        width: "100%",
        justifyContent: "space-evenly",
    },
    deleteModalBtn: {
        flex: 1,
        textAlign: "center",
        textAlignVertical: "center",
        fontSize: 14,
        fontWeight: "bold",
        color: colors.red,
        borderLeftColor: colors.gray,
        borderLeftWidth: 0.5,
    },
    cancelModalBtn: {
        flex: 1,
        textAlign: "center",
        textAlignVertical: "center",
        fontSize: 14,
        fontWeight: "bold",
        color: colors.gray,
    },
    modalView: {
        padding: 16,
        alignItems: "center",
    },
    buttonOpen: {
        justifyContent: "center",
        alignItems: "center",
    },
    buttonClose: {
        backgroundColor: "#2196F3",
        height: 30,
        width: "33%",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 15,
        elevation: 2,
    },
    textStyle: {
        color: "gray",
        textAlign: "center",
    },
    modalText: {
        textAlign: "center",
    },
    hideModalButton: {
        color: "white",
    },
    confirmBtnWrapper: {
        alignSelf: "center",
        backgroundColor: colors.blue,
        width: 344,
        height: 50,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 10,
    },
    confirmBtnText: {
        color: "#fff",
        fontSize: 17,
    },
    loader: {
        // marginTop: 10,
        alignItems: "center",
    },
});
